# Default values for cp-kafka-mirror-maker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image: confluentinc/cp-kafka
imageTag: "5.4.2"

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: Always

## Specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets:

servicePort: 8083

## Kafka MirrorMaker JVM Heap Option
heapOptions: "-Xms1024M -Xmx1024M"

## Additional env variables
customEnv: {}

resources:
  limits:
   cpu: 500m
   memory: 2Gi
  requests:
   cpu: 500m
   memory: 2Gi

## Custom pod annotations
podAnnotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## Taints to tolerate on node assignment:
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}

## Monitoring
## Kafka MirrorMaker JMX Settings
## ref: https://kafka.apache.org/documentation/#monitoring
jmx:
  port: 9998
  enabled: true

## Prometheus Exporter Configuration
## ref: https://prometheus.io/docs/instrumenting/exporters/
prometheus:
  ## JMX Exporter Configuration
  ## ref: https://github.com/prometheus/jmx_exporter
  jmx:
    image: solsson/kafka-prometheus-jmx-exporter@sha256
    imageTag: 70852d19ab9182c191684a8b08ac831230006d82e65d1db617479ea27884e4e8
    port: 5556

    ## Resources configuration for the JMX exporter container.
    ## See the `resources` documentation above for details.
    resources: {}

## You can list load balanced service endpoint, or list of all brokers (which is hard in K8s).  e.g.:
## bootstrapServers: "PLAINTEXT://prod-kafka-0:9092"
kafka:
  topicWhitelist:
  topicBlacklist:
  numStreams: "1"
  producerConfig:
    bootstrap.servers: "localhost:9094"
    security.protocol: SSL
    ssl.truststore.location: /usr/lib/jvm/zulu-8-amd64/jre/lib/security/cacerts
  consumerConfig:
    bootstrap.servers: "localhost:9094"
    security.protocol: SSL
    ssl.truststore.location: /usr/lib/jvm/zulu-8-amd64/jre/lib/security/cacerts
