# Default values for vvpflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image: 3bittechs/vvpflow
imageTag: "1.0"

## Specify a imagePullPolicy
## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
imagePullPolicy: Always

## Specify an array of imagePullSecrets.
## Secrets must be manually created in the namespace.
## ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets:

vvpflow:
  env: {}

git:
  env: {}
  additionalVolumeMounts: []
  additionalVolumes: []
resources:
  limits:
   cpu: 500m
   memory: 2Gi
  requests:
   cpu: 500m
   memory: 2Gi

## Custom pod annotations
podAnnotations: {}

## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
nodeSelector: {}

## Taints to tolerate on node assignment:
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: {}