apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "vvpflow.fullname" . }}
  labels:
    app: {{ template "vvpflow.name" . }}
    chart: {{ template "vvpflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vvpflow.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vvpflow.name" . }}
        release: {{ .Release.Name }}
      {{- if .Values.podAnnotations }}
      annotations:
      {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
    spec:
      containers:
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.3
          volumeMounts:
          - name: deployments
            mountPath: /usr/src/repos
        {{- if .Values.git.additionalVolumeMounts }}
{{ toYaml .Values.git.additionalVolumeMounts | indent 10 }}
        {{- end}}
        {{- if .Values.git.resources }}
          resources:
{{ toYaml .Values.git.resources | indent 12 }}
        {{- end }}
          {{- if .Values.git.env }}
          env:
          {{- range $key, $value := .Values.git.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- end }}
        - name: {{ template "vvpflow.name" . }}-server
          image: "{{ .Values.image }}:{{ .Values.imageTag }}"
          volumeMounts:
          - name: deployments
            mountPath: /usr/src/repos
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
        {{- if .Values.vvpflow.resources }}
          resources:
{{ toYaml .Values.vvpflow.resources | indent 12 }}
        {{- end }}
      {{- if .Values.vvpflow.env }}
          env:
          {{- range $key, $value := .Values.vvpflow.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      volumes:
        - name: deployments
          emptyDir: {}
      {{- if .Values.git.additionalVolumes }}
{{ toYaml .Values.git.additionalVolumes | indent 8 }}
      {{- end }}