replicaCount: 1
image:
  repository: 3bittechs/alertmanager-cloudwatch:latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
container:
  port: 8077  
resources:
   limits:
     cpu: 0.1
     memory: 50Mi
namespace: "monitoring"
serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789123:role/xyz
securityContext:
  fsGroup: 472
  runAsGroup: 472
  runAsUser: 472
awsRegion: "us-east-1"
ginMode: "release"
cloudwatchNamespace: "Prometheus"
snsArn: "arn:aws:sns:us-east-1:123123:sns_test"
