replicaCount: 1
image:
  repository: 3bittechs/alertmanager-cloudwatch/alertmanager-cloudwatch:latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
container:
  port: 8077  
resources:
   limits:
     cpu: 0.1
     memory: 50Mi
namespace: "monitoring"
